### ISSUE TITLE
inference on custom data is noise.

### ISSUE THREAD

**Issue by vivasvan1** [weihaosky/MFuseNet#2]
When predicting on my images I am getting only noise. Any reason why?

Left:

![KLE_1113 jpg4_half](https://user-images.githubusercontent.com/21074796/95105686-250aa000-0755-11eb-9b97-2aad2727a56d.png)

Right:
![KLE_1113 jpg5_half](https://user-images.githubusercontent.com/21074796/95106378-11ac0480-0756-11eb-8559-4a9633d61158.png)

Output:

![orig2_outdisp](https://user-images.githubusercontent.com/21074796/95103269-0e167e80-0752-11eb-88f2-371c30c3c87a.png)

**Comment by vivasvan1** [comment]
I have set max_disp to 60.

**Comment by weihaosky** [comment]
Not sure. The output is from my pretrained model? Is the output from MC-CNN normal? 
Maybe you can try torch=1.1.0 torchvision=0.2.0. Models trained by different-version torchvision may cause problems.
By the way, your left-right images look no disparity in most places. Are they taken by stereo camera?
